version: '3'
services:
        itemdb:
                image: postgres:latest
                ports:
                        - '5433:5432'
        web-app:
                build:
                        context: ./frontend
                        dockerfile: Dockerfile.dev
                volumes:
                        - /app/node_modules
                        - ./frontend:/app
                ports:
                        - '3000:3000'
                restart: on-failure
                container_name: web-app
        item-api:
                build:
                        context: ./backend
                        dockerfile: Dockerfile.dev
                ports:
                        - '3001:3001'
                restart: on-failure
                container_name: item-api
                volumes:
                        - /app/node_modules
                        - ./backend:/app
                environment:
                        - PGUSER=postgres
                        - PGHOST=itemdb
                        - PGDATABASE=postgres
                        - PGPASSWORD=
                        - PGPORT=5432
