version: '3'
services:
        itemdb:
                image: postgres:latest
                ports:
                        - '5433:5432'
                volumes:
                        - ./pgdata:/var/lib/postgresql/data
        web-app:
                build:
                        context: ./frontend
                        dockerfile: Dockerfile.dev
                volumes:
                        - /app/node_modules
                        - ./frontend:/app
                ports:
                        - '1234:1234'
                restart: on-failure
                container_name: web-app
                environment:
                        - PORT=1234
                        - REACT_APP_ITEMS_API=http://localhost:3333/v1
        item-api:
                build:
                        context: ./backend
                        dockerfile: Dockerfile.dev
                ports:
                        - '3333:3333'
                restart: on-failure
                container_name: item-api
                volumes:
                        - /app/node_modules
                        - ./backend:/app
                environment:
                        - PGUSER=postgres
                        - PGHOST=itemdb
                        - PGDATABASE=postgres
                        - PGPASSWORD=
                        - PGPORT=5432
                        - PORT=3333
